name: Cypress Tests

on: [pull_request, workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::270665662100:role/blogsite-ec2-role
          role-session-name: MySessionName
      
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          build: npm run build
          start: npm start
